import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Link,useNavigate} from 'react-router-dom';
import markup from './design/home.html?raw';
import {useStore} from './context';
import {money} from './api';
import {ProductCard,Empty} from './components';

function CategoryArt({style}) {return style==='baby'?<svg className="cat-art" viewBox="0 0 130 160"><circle cx="65" cy="80" r="54" fill="#fff" opacity=".55"/><path d="M49 44h32l5 87H44z" fill="#674493"/><rect x="56" y="25" width="20" height="24" rx="7" fill="#4B2E83"/><text x="65" y="91" textAnchor="middle" fill="white" fontSize="13" fontFamily="Georgia">B&amp;B</text></svg>:style==='toys'?<svg className="cat-art" viewBox="0 0 160 130"><path d="M26 67h108l-16 18H43z" fill="#c58c52"/><rect x="74" y="27" width="12" height="71" rx="6" fill="#9d6b3d" transform="rotate(90 80 63)"/><path d="M80 39 51 15h17l22 18M80 84l-24 24h18l19-21" fill="#d6a469"/><circle cx="49" cy="89" r="10" fill="#82552f"/><circle cx="112" cy="89" r="10" fill="#82552f"/></svg>:style==='beauty'?<svg className="cat-art" viewBox="0 0 130 160"><rect x="48" y="62" width="36" height="72" rx="8" fill="#d9ad5b"/><path d="M58 61h16l-4-18H62z" fill="#c7913e"/><circle cx="66" cy="31" r="14" fill="#fff" opacity=".85"/><text x="66" y="104" textAnchor="middle" fill="#fff" fontSize="12" fontFamily="Georgia">B&amp;B</text></svg>:<svg className="cat-art" viewBox="0 0 150 150"><rect x="26" y="54" width="98" height="74" rx="7" fill="#553280"/><rect x="68" y="54" width="16" height="74" fill="#c7a6df"/><rect x="20" y="46" width="110" height="24" rx="5" fill="#6b4697"/><path d="M75 46C53 28 50 15 63 13c13-2 17 19 12 33Zm0 0c22-18 25-31 12-33-13-2-17 19-12 33Z" fill="#e7d7f3"/></svg>;}
export default function Home(){const{store,products,add,notify}=useStore();const root=useRef(),[slots,setSlots]=useState({}),[filter,setFilter]=useState('Best Seller'),[chosen,setChosen]=useState([]);const navigate=useNavigate();const gifts=products.filter(p=>p.giftEligible&&!p.variants.length&&p.stock>0).slice(0,6);const picks=products.filter(p=>p.tag===filter);const s=store.settings;
 useLayoutEffect(()=>{setSlots(Object.fromEntries(['productGrid','homeCategories','bundleOptions','homeCommunity'].map(id=>[id,root.current.querySelector('#'+id)])));const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in');}),{threshold:.05});root.current.querySelectorAll('.reveal').forEach(e=>observer.observe(e));return()=>observer.disconnect();},[]);
 useEffect(()=>{const node=root.current;const text=(sel,value)=>{const el=node.querySelector(sel);if(el)el.textContent=value;};text('.hero h1',s.heroTitle);const title=node.querySelector('.hero h1');title.append(document.createElement('br'));const em=document.createElement('em');em.textContent=s.heroAccent;title.append(em);text('.hero-copy p',s.heroDescription);const eyebrow=node.querySelector('.eyebrow');eyebrow.lastChild.textContent=' '+s.heroEyebrow;text('.story h2',s.storyTitle);text('.story p',s.storyDescription);text('#shop .section-head p',s.categoryDescription);text('.products-section .section-head p',s.productDescription);text('.community .section-head p',s.communityDescription);node.querySelector('.brand-orb img').src=s.logo;node.querySelector('.community').hidden=!s.showCommunity;node.querySelector('.bundle').hidden=!s.showBundles;node.querySelector('.spotlight').style.gridTemplateColumns=s.showBundles?'':'1fr';text('.service-item small',s.freeShippingMin?'Orders above '+money(s.freeShippingMin):'Delivery across Bangladesh');},[s]);
 useEffect(()=>{const node=root.current;node.querySelector('#productResult').textContent=picks.length+' curated picks';node.querySelectorAll('.tab').forEach(el=>el.classList.toggle('active',el.dataset.filter===filter));node.querySelector('#bundleCount').textContent=chosen.length;node.querySelector('#bundleTotal').textContent=money(chosen.reduce((n,id)=>n+(products.find(p=>p.id===id)?.price||0),0));node.querySelector('#bundleProgress').style.width=(chosen.length/3*100)+'%';},[filter,chosen,products]);
 useEffect(()=>{const art=root.current.querySelector('#heroArt'),stage=root.current.querySelector('#productStage');if(!matchMedia('(pointer:fine)').matches)return;const move=e=>{const r=art.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;stage.style.transform=`rotateY(${x*10}deg) rotateX(${-y*8}deg) translate3d(${x*8}px,${y*7}px,0)`;};const leave=()=>stage.style.transform='';art.addEventListener('mousemove',move);art.addEventListener('mouseleave',leave);return()=>{art.removeEventListener('mousemove',move);art.removeEventListener('mouseleave',leave);};},[]);
 function click(e){const tab=e.target.closest('[data-filter]');if(tab)setFilter(tab.dataset.filter);const a=e.target.closest('a');if(a?.getAttribute('href')?.startsWith('/')){e.preventDefault();navigate(a.getAttribute('href'));}if(e.target.closest('#bundleAdd')){if(chosen.length!==3)return notify('Choose exactly 3 favorites for your gift box.');chosen.forEach(id=>add(products.find(p=>p.id===id)));setChosen([]);notify('Your three gift picks have been added to your bag.');}}
 return <>{store.banners.length>0&&<div className="campaigns shell">{store.banners.map(b=><Link key={b.id} to={b.link}><img src={b.image} alt={b.title}/><span><b>{b.title}</b>{b.subtitle}</span></Link>)}</div>}<div ref={root} onClick={click} dangerouslySetInnerHTML={{__html:markup}}/>{slots.productGrid&&createPortal(picks.length?picks.map(p=><ProductCard key={p.id} p={p}/>):<Empty title="More favorites are on their way.">Explore all our collections.</Empty>,slots.productGrid)}{slots.homeCategories&&createPortal(store.categories.filter(c=>!c.parentId).map(c=><Link key={c.id} className={'cat cat-'+c.style+' reveal in'} to={'/shop?category='+c.slug}><h3>{c.name}</h3><p>{c.description}</p><div className="arrow">→</div>{c.image?<img className="cat-art" src={c.image} alt=""/>:<CategoryArt style={c.style}/>}</Link>),slots.homeCategories)}{slots.bundleOptions&&createPortal(gifts.map(p=><button key={p.id} className={'bundle-chip '+(chosen.includes(p.id)?'active':'')} aria-pressed={chosen.includes(p.id)} onClick={()=>{if(!chosen.includes(p.id)&&chosen.length===3)return notify('Your gift box already has 3 picks.');setChosen(c=>c.includes(p.id)?c.filter(id=>id!==p.id):[...c,p.id]);}}><div className="chip-art">{p.images[0]?<img src={p.images[0]} alt=""/>:p.type==='toy'?'🧸':p.type==='gift'?'🎀':p.type==='oil'?'✨':p.type==='jar'?'🫧':'🧴'}</div>{p.name}</button>),slots.bundleOptions)}{slots.homeCommunity&&createPortal(s.communityItems.map((c,i)=><div className="ugc reveal in" key={i}>{c.image?<img src={c.image} alt={c.label}/>:<div className="emoji">{c.emoji}</div>}<span>{c.label}</span></div>),slots.homeCommunity)}</>;
}
